---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: watchstate
  namespace: media
spec:
  components:
    - ../../../../components/oidc/envoy
    - ../../../../components/kopiur/backup
  dependsOn:
    - name: pocket-id
      namespace: security
    - name: kopiur
      namespace: kopiur-system
  interval: 30m
  path: ./kubernetes/apps/media/watchstate/app
  postBuild:
    substitute:
      APP: watchstate
      APP_ICON_URL: "https://cdn.jsdelivr.net/gh/selfhst/icons/webp/watchstate.webp"
      OIDC_APP_NAME: Watch Sync (Watchstate)
      KOPIUR_CAPACITY: 10Gi
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true 
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  timeout: 5m
  wait: false