---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: patchmon
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: patchmon-secret
    template:
      data:
        JWT_SECRET: "{{ .JWT_SECRET }}"
        SESSION_SECRET: "{{ .SESSION_SECRET }}"
        AI_ENCRYPTION_KEY: "{{ .AI_ENCRYPTION_KEY }}"
        POSTGRES_HOST: main-rw.databases
        POSTGRES_PASSWORD: "{{ .MAIN_APP_PASSWORD }}"
        POSTGRES_USER: "{{ .MAIN_APP_USERNAME }}"
        POSTGRES_DB: patchmon
        DATABASE_URL: "postgresql://{{ .MAIN_APP_USERNAME }}:{{ .MAIN_APP_PASSWORD }}@main-rw.databases:5432/patchmon"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: patchmon