---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: patchmon
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: patchmon-secret
    template:
      data:
        JWT_SECRET: "{{ .JWT_SECRET }}"
        SESSION_SECRET: "{{ .SESSION_SECRET }}"
        AI_ENCRYPTION_KEY: "{{ .AI_ENCRYPTION_KEY }}"
        DATABASE_URL: postgresql://"{{ .appUser }}":"{{ .appPassword }}"@main-db-rw.databases:5432/patchmon
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: patchmon