---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app patchmon
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/patchmon/patchmon-server
              tag: 2.0.2@sha256:eaa1bcce290c7003cff01a96cfc893a64cb144e582e9b797875e6381f56b297a
            env:
              TZ: America/New_York
              # Logging
              ENABLE_LOGGING: true
              LOG_LEVEL: debug
              PORT: &port 80
              CORS_ORIGIN: "https://{{ .Release.Name }}.noms.tv"
              # Rate limiting
              RATE_LIMIT_WINDOW_MS: "900000"
              RATE_LIMIT_MAX: "5000"
              AUTH_RATE_LIMIT_WINDOW_MS: "600000"
              AUTH_RATE_LIMIT_MAX: "500"
              AGENT_RATE_LIMIT_WINDOW_MS: "60000"
              AGENT_RATE_LIMIT_MAX: "1000"
              # Redis configuration
              REDIS_HOST: patchmon-valkey
              REDIS_PORT: "6379"
              REDIS_DB: "0"
              # Security
              # Trust proxy headers from ingress controller and internal cluster networks
              TRUST_PROXY: "true"
              ENABLE_HSTS: false
              # User management
              DEFAULT_USER_ROLE: "user"
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: *port
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness: *probes
              startup: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.noms.tv"
        parentRefs:
          - name: envoy-internal
            namespace: network