---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: swin
  namespace: virtualization
spec:
  dependsOn:
    - name: kubevirt
    - name: cdi
  interval: 1h
  path: ./kubernetes/apps/virtualization/swin/app
  components:
    - ../../../../components/volsync
  postBuild:
    substitute:
      APP: swin
      VOLSYNC_CAPACITY: 275Gi
      VOLSYNC_SCHEDULE: "0 0/12 * * *"
      VOLSYNC_HOURLY: "4"
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: virtualization
  timeout: 5m
  wait: false
