---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ubuntu-test
  namespace: virtualization
spec:
  dependsOn:
    - name: kopiur
      namespace: kopiur-system
    - name: kubevirt
    - name: cdi
    - name: multus
      namespace: kube-system
  interval: 1h
  path: ./kubernetes/apps/virtualization/ubuntu-test/app
  components:
    - ../../../../components/kopiur/backup
  postBuild:
    substitute:
      APP: ubuntu-test
      KOPIUR_CAPACITY: 50Gi
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: virtualization
  timeout: 5m
  wait: false
