---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: postgis-app
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: onepassword-connect
      kind: ClusterSecretStore
  selector:
    secret:
      name: postgis-app
  template:
    engineVersion: v2
    data:
      POSTGIS_APP_USERNAME: '{{ index . "username" }}'
      POSTGIS_APP_PASSWORD: '{{ index . "password" }}'
  data:
    - match:
        secretKey: &key POSTGIS_APP_USERNAME
        remoteRef:
          remoteKey: cloudnative-pg
          property: *key
    - match:
        secretKey: &key POSTGIS_APP_PASSWORD
        remoteRef:
          remoteKey: cloudnative-pg
          property: *key