---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../components/cluster-secrets
resources:
  ## Requisites
  - ./namespace.yaml
  ## Deployments
  - ./auditorr/ks.yaml
  - ./aurral/ks.yaml
  - ./autobrr/ks.yaml
  - ./cleanuparr/ks.yaml
  - ./cmdarr/ks.yaml
  - ./kometa/ks.yaml
  - ./lidarr/ks.yaml
  - ./maintainerr/ks.yaml
  - ./navidrome/ks.yaml
  - ./plex/ks.yaml
  - ./posterizarr/ks.yaml
  - ./profilarr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./readarr/ks.yaml
  - ./seerr/ks.yaml
  - ./slskd/ks.yaml
  - ./sonarr/ks.yaml
  - ./tracearr/ks.yaml
  - ./unpackerr/ks.yaml
  - ./watchstate/ks.yaml
