---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: pocket-id-secret
    template:
      engineVersion: v2
      data:
        encryptionKey: "{{ .encryptionKey }}"
        databaseUrl: postgresql://{{ .MAIN_APP_USERNAME }}:{{ .MAIN_APP_PASSWORD }}@main-rw.databases:5432/pocket-id
        smtpUsername: "{{ .smtpUsername }}"
        smtpToken: "{{ .smtpToken }}"
        maxmindLicenseKey: "{{ .licenseKey }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: maxmind
    - extract:
        key: pocket-id
    - extract:
        key: SMTP