---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDUserGroup
metadata:
  name: financal-services
spec:
  friendlyName: Financal Services
  allowedOIDCClients:
    - name: wallos
---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDUserGroup
metadata:
  name: llm-users
spec:
  friendlyName: LLM Users
  allowedOIDCClients:
    - name: openclaw
---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDUserGroup
metadata:
  name: media-users
spec:
  friendlyName: Media Service Users
  allowedOIDCClients:
    - name: navidrome
    - name: prowlarr
    - name: radarr
    - name: readarr
    - name: sonarr
    - name: sonarr-kids
    - name: watchstate
---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDUserGroup
metadata:
  name: emby-users
spec:
  friendlyName: Emby Users
  allowedOIDCClients:
    - name: emby
