---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reitti
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: reitti
  values:
    controllers:
      reitti:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/dedicatedcode/reitti
              tag: 5.1.0@sha256:f97f94df5b18e6f8c12774e4f421b234c74f2a258b77247320a445a697b8fb17
            env:
              DISABLE_LOCAL_LOGIN: "true"
              OIDC_ENABLED: "true"
              POSTGIS_DB: "{{ .Release.Name }}"
              POSTGIS_HOST: postgis-rw.databases
              REDIS_HOST: dragonfly.databases
              REDIS_DATABASE: "6"
              SERVER_PORT: &port 8080
              TILES_CACHE: http://reitti-tile-cache
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness: &probes
                enabled: false
                custom: true
                spec:
                  tcpSocket:
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 2Gi
          tile-cache:
            image:
              repository: ghcr.io/dedicatedcode/reitti-tile-cache
              tag: 5.1.0@sha256:98a96e6df5948a80e731193f4e5e4f0d5c4263beee13ea5980561db0ef7030b9
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
      tile-cache:
        ports:
          http:
            port: 80
    route:
      app:
        hostnames:
          - "location.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
      tile-cache:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        forceRename: "{{ .Release.Name }}-cache"
        size: 10Gi
        storageClass: ceph-block
        advancedMounts:
          reitti:
            tile-cache:
              - path: /var/cache/nginx