---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reitti
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: reitti
  values:
    controllers:
      reitti:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/dedicatedcode/reitti
              tag: 5.0.2@sha256:75bc2f165d4dd14605e181539d9e8759d1c5fb6d655fa90950ad721dfafaf504
            env:
              OIDC_ENABLED: "true"
              POSTGIS_DB: "{{ .Release.Name }}"
              POSTGIS_HOST: postgis-rw.databases
              REDIS_HOST: dragonfly.databases
              REDIS_DATABASE: "6"
              SERVER_PORT: &port 80
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness: &probes
                enabled: false
                custom: true
                spec:
                  tcpSocket:
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 1Gi
          tile-cache:
            image:
              repository: ghcr.io/dedicatedcode/reitti-tile-cache
              tag: 5.0.2@sha256:5fde90772a1fe5d330bdae3e47db425b977730f953039ada473d62531b60fbdf
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 512Mi
    service:
      app:
        ports:
          http:
            port: *port
      tile-cache:
        ports:
          http:
            port: 80
    route:
      app:
        hostnames:
          - "location.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
      tile-cache:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 10Gi
        storageClass: ceph-block
        advancedMounts:
          reitti:
            tile-cache:
              - path: /var/cache/nginx