---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cmdarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cmdarr-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        CMDARR_AUTH_USERNAME: "{{ .CMDARR_AUTH_USERNAME }}"
        CMDARR_AUTH_PASSWORD: "{{ .CMDARR_AUTH_PASSWORD }}"
        CMDARR_API_KEY: "{{ .CMDARR_API_KEY }}"
        LIDARR_API_KEY: "{{ .LIDARR_API_KEY }}"
        PLEX_TOKEN: "{{ .PlexToken }}"
        LISTENBRAINZ_TOKEN: "{{ .LISTENBRAINZ_TOKEN }}"
        LISTENBRAINZ_USERNAME: "{{ .LISTENBRAINZ_USER }}"
  dataFrom:
    - extract:
        key: cmdarr
    - extract:
        key: plex
    - extract:
        key: lidarr