---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cmdarr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: cmdarr
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      cmdarr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/devianteng/cmdarr
              tag: v0.3.17@sha256:468cac8c5f83c7b475ed4cdaafa7d7b9d708f9314e163d54acf310036ae4861f
            env:
              DEFAULT_SCHEDULE_CRON: 0 3 * * *
              PUID: 1000
              PGID: 1000
              LIDARR_URL: http://lidarr
              MAX_PARALLEL_COMMANDS: 2
              MUSICBRAINZ_ENABLED: true
              PLEX_URL: http://plex:32400
              SCHEDULER_TIMEZONE: America/New_York
              WEB_PORT: &port 80
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            # probes:
            #   liveness:
            #     enabled: true
            #     spec:
            #       periodSeconds: 30
            #       timeoutSeconds: 5
            #       failureThreshold: 5
            #   readiness:
            #     enabled: true
            #     custom: true
            #     spec:
            #       httpGet:
            #         path: /
            #         port: *port
            #       periodSeconds: 10
            #       timeoutSeconds: 5
            #       failureThreshold: 5
            #   startup:
            #     enabled: true
            #     spec:
            #       failureThreshold: 30
            #       periodSeconds: 10
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 512Mi
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.noms.tv"
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /app/data