---
apiVersion: v1
kind: ConfigMap
metadata:
  name: deduparr-config
data:
  config.yaml: |
    schedule: service
    action: dry-run
    log_level: info
    log_format: text

    remove_from_client: false

    service:
      interval: 5min
      port: 9090

    database:
      url:
        file: /var/run/secrets/postgres/url

    radarr:
      - name: radarr
        url: http://radarr

    sonarr:
      - name: sonarr
        url: http://sonarr
      - name: sonarr-kids
        url: http://sonarr-kids

    client_api:
      timeout: 5s
      retry:
        max_times: 3 
        min_delay: 1s
        max_delay: 4s
