---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: deduparr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: deduparr-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DEDUPARR_RADARR_RADARR_API_KEY: "{{ .RadarrAPIKey }}"
        DEDUPARR_SONARR_SONARR_API_KEY: "{{ .SonarrAPIKey }}"
  dataFrom:
    - extract:
        key: arr-apps