---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: deduparr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: deduparr
  values:
    controllers:
      deduparr:
        forceRename: deduparr
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: git.enoent.fr/kernald/deduparr
              tag: 1.2.0@sha256:6e579f684a147dcd2dcd4468c50ffb0848e23b8306f1355037a2419931fe4b7f
            env:
              DEDUPARR_SCHEDULE: service
              DEDUPARR_ACTION: remove
              DEDUPARR_LOG_LEVEL: info
              DEDUPARR_LOG_FORMAT: text
              DEDUPARR_REMOVE_FROM_CLIENT: false
              DEDUPARR_SERVICE__PORT: &port 9090
              DEDUPARR_SERVICE__INTERVAL: 5m
              DEDUPARR_RADARR_MAIN_URL: http://radarr
              DEDUPARR_SONARR_MAIN_URL: http://sonarr
              DEDUPARR_SONARR_KIDS_URL: http://sonarr-kids
              DEDUPARR_DATABASE_URL:
                valueFrom:
                  secretKeyRef:
                    name: deduparr-postgres
                    key: url
            envFrom:
              - secretRef:
                  name: deduparr-secret
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health/live
                    port: *port
                  periodSeconds: 30
                  timeoutSeconds: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health/ready
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 5
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health/live
                    port: *port
                  failureThreshold: 30
                  periodSeconds: 5
                  timeoutSeconds: 5
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 2Gi

    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    persistence:
      postgres:
        type: secret
        name: deduparr-postgres
        globalMounts:
          - path: /var/run/secrets/postgres
            readOnly: true

    service:
      app:
        controller: deduparr
        forceRename: deduparr
        ports:
          http:
            port: *port