---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: readarr
  namespace: default
spec:
  components:
    - ../../../../components/oidc/envoy
    - ../../../../components/volsync
  dependsOn:
    - name: pocket-id
      namespace: security
    - name: volsync
      namespace: volsync-system
  interval: 30m
  path: ./kubernetes/apps/default/readarr/app
  postBuild:
    substitute:
      APP: readarr
      APP_ICON_URL: "https://cdn.jsdelivr.net/gh/selfhst/icons/svg/readarr.svg"
      OIDC_APP_NAME: Book Requests (Readarr)
      VOLSYNC_CAPACITY: 5Gi
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true 
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  timeout: 5m
  wait: false