---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: technitium-dns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: technitium-dns-secret
    template:
      data:
        EXTERNAL_DNS_RFC2136_TSIG_SECRET: "{{ .TSIG_KEY }}"
        EXTERNAL_DNS_RFC2136_TSIG_KEYNAME: "{{ .TSIG_KEY_NAME }}"
        EXTERNAL_DNS_RFC2136_ZONE: "{{ .ZONE }}"
  dataFrom:
    - extract:
        key: technitium
