---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: llama-cpp
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: llama-cpp-secret
    creationPolicy: Owner
    template:
      data:
        HF_TOKEN: "{{ .HF_TOKEN }}"
        LLAMA_API_KEY: "{{ .LLAMA_API_KEY }}"
  dataFrom:
    - extract:
        key: llama-cpp