---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radicale
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: radicale
  values:
    controllers:
      radicale :
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/kozea/radicale
              tag: stable@sha256:ff012f461abd60a439eeee983c4b3de73ca477e6045c439a95e0e1bd81e3482e
            env:
              TZ: America/New_York
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: &port 5232
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 256Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "calendar.noms.tv"
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
    persistence:
      config:
        type: secret
        name: radicale
        globalMounts:
          - path: /etc/radicale/config
            subPath: config
      users:
        type: secret
        name: radicale
        globalMounts:
          - path: /etc/radicale/users
            subPath: users
      data:
        existingClaim: "{{ .Release.Name }}"