---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: open-webui-secret
    creationPolicy: Owner
    template:
      data:
        WEBUI_SECRET_KEY: "{{ .WEBUI_SECRET_KEY }}"
        OAUTH_CLIENT_ID: "{{ .OAUTH_CLIENT_ID }}"
        OAUTH_CLIENT_SECRET: "{{ .OAUTH_CLIENT_SECRET }}"
        OPENID_PROVIDER_URL: "{{ .OPENID_PROVIDER_URL }}"
        OPENID_REDIRECT_URI: "{{ .OPENID_REDIRECT_URI }}"
  dataFrom:
    - extract:
        key: open-webui
