# ---
# # yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: paperless-ai
#   namespace: default
# spec:
#   components:
#     - ../../../../components/kopiur/backup
#   dependsOn:
#     - name: kopiur
#       namespace: kopiur-system
#   interval: 30m
#   path: ./kubernetes/apps/default/paperless/ai
#   postBuild:
#     substitute:
#       APP: paperless-ai
#       KOPIUR_CAPACITY: 10Gi
#     substituteFrom:
#       - name: cluster-secrets
#         kind: Secret
#   prune: true 
#   retryInterval: 1m
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#     namespace: flux-system
#   targetNamespace: default
#   timeout: 5m
#   wait: false
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: paperless
  namespace: default
spec:
  components:
    - ../../../../components/kopiur/backup
    - ../../../../components/kopiur/migrate
  dependsOn:
    - name: kopiur
      namespace: kopiur-system
  interval: 30m
  path: ./kubernetes/apps/default/paperless/app
  postBuild:
    substitute:
      APP: paperless
      KOPIUR_CAPACITY: 100Gi
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true 
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  timeout: 5m
  wait: false
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: paperless-gotenberg
  namespace: default
spec:
  interval: 30m
  path: ./kubernetes/apps/default/paperless/gotenberg
  postBuild:
    substitute:
      APP: paperless-gotenberg
  prune: true 
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  timeout: 5m
  wait: false
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: paperless-tika
  namespace: default
spec:
  interval: 30m
  path: ./kubernetes/apps/default/paperless/tika
  postBuild:
    substitute:
      APP: paperless-tika
  prune: true 
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  timeout: 5m
  wait: false