apiVersion: apps/v1
kind: Deployment
metadata:
  name: &app forgejo-runner-home-ops
  labels:
    app: *app
    app.kubernetes.io/component: *app
    app.kubernetes.io/instance: *app
    app.kubernetes.io/managed-by: Kustomize
    app.kubernetes.io/name: *app
spec:
  replicas: 7
  selector:
    matchLabels:
      app: *app
  template:
    metadata:
      name: *app
      labels:
        app: *app
        app.kubernetes.io/component: *app
        app.kubernetes.io/instance: *app
        app.kubernetes.io/managed-by: Kustomize
        app.kubernetes.io/name: *app
    spec:
      automountServiceAccountToken: false
      restartPolicy: Always
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: *app
      containers:
        - name: runner
          # renovate: datasource=forgejo-releases depName=containers/forgejo-home-ops-runner registryUrl=https://git.noms.tv packageName=containers/forgejo-home-ops-runner
          image: git.noms.tv/containers/forgejo-home-ops-runner:12.8.2@sha256:c2d2e18d90c13cd0ec7397cc69dc6dce407042296a881ba28b5dc38e0f1042e9
          env:
            - name: NODE
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: FORGEJO_RUNNER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TALOSCONFIG
              value: /var/run/secrets/talos.dev/config
          envFrom:
            - secretRef:
                name: forgejo-runner-home-ops-secret
          resources:
            limits:
              cpu: '1'
              ephemeral-storage: 3Gi
              memory: 4Gi
            requests:
              cpu: 100m
              ephemeral-storage: '0'
              memory: 64Mi
          volumeMounts:
            - name: runner-data
              mountPath: /data
            - name: tmp
              mountPath: /tmp
            - name: talos
              mountPath: /var/run/secrets/talos.dev
              readOnly: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {drop: ["ALL"]}
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: runner-data
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: talos
          secret:
            secretName: *app