---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner-home-ops
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: forgejo-runner-home-ops-secret
    template:
      data:
        FORGEJO_URL: '{{ .FORGEJO_URL }}'
        FORGEJO_RUNNER_LABELS: "home-ops-runner:host"
        FORGEJO_RUNNER_NAME: home-ops-runner
        FORGEJO_RUNNER_SECRET: '{{ .FORGEJO_HOME_OPS_RUNNER_SECRET }}'
  dataFrom:
    - extract:
        key: forgejo-runner
