---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: readarr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: readarr
  values:
    controllers:
      readarr :
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: lscr.io/linuxserver/readarr
              tag: develop-version-0.4.17.2801@sha256:f3978bd06611493011137d82ebdd5e49b3ebb17ad921dbd05017d40b7f2000e3
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 1Gi

    defaultPodOptions:
      annotations:
        k8s.v1.cni.cncf.io/networks: |-
          [{
            "name": "vpn",
            "namespace": "kube-system",
            "ips": ["10.1.66.9/24"],
            "mac": "00:00:10:01:66:09"
          }]
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        ports:
          http:
            port: 8787

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - name: protected
            backendRefs:
              - identifier: app
                port: http

    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      media:
        type: nfs
        server: truenas.services
        path: /mnt/BigPool/Media