---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  ## Requisites
  - ./namespace.yaml
  ## Deployments
  - ./actual-budget/ks.yaml
  - ./audiobookshelf/ks.yaml
  - ./cleanuparr/ks.yaml
  - ./homepage/ks.yaml
  - ./immich/ks.yaml
  - ./karakeep/ks.yaml
  - ./kometa/ks.yaml
  - ./linkwarden/ks.yaml
  - ./lubelogger/ks.yaml
  - ./maintainarr/ks.yaml
  - ./mealie/ks.yaml
  - ./music-assistant/ks.yaml
  # - ./openwakeword/ks.yaml
  - ./paperless/ks.yaml
  # - ./piper/ks.yaml
  - ./plex/ks.yaml
  - ./plex-auto-languages/ks.yaml
  - ./posterizarr/ks.yaml
  - ./profilarr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./radarr/ks.yaml
  - ./radicale/ks.yaml
  - ./readarr/ks.yaml
  - ./reitti/ks.yaml
  - ./seedboxapi/ks.yaml
  - ./seerr/ks.yaml
  - ./sonarr/ks.yaml
  - ./spoolman/ks.yaml
  - ./tracearr/ks.yaml
  - ./unpackerr/ks.yaml
  - ./wallos/ks.yaml
  - ./watchstate/ks.yaml
  # - ./whisper/ks.yaml
  - ./wikijs/ks.yaml