---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/cluster-secrets
resources:
  ## Requisites
  - ./namespace.yaml
  ## Deployments
  - ./actual-budget/ks.yaml
  - ./audiobookshelf/ks.yaml
  - ./homepage/ks.yaml
  - ./immich/ks.yaml
  - ./karakeep/ks.yaml
  - ./lubelogger/ks.yaml
  - ./mealie/ks.yaml
  - ./music-assistant/ks.yaml
  - ./ntfy/ks.yaml
  # - ./openwakeword/ks.yaml
  - ./paperless/ks.yaml
  - ./patchmon/ks.yaml
  # - ./piper/ks.yaml
  - ./profilarr/ks.yaml
  - ./qui/ks.yaml
  - ./radicale/ks.yaml
  - ./reitti/ks.yaml
  - ./seasonpackerr/ks.yaml
  - ./spoolman/ks.yaml
  - ./thelounge/ks.yaml
  - ./wallos/ks.yaml
  # - ./whisper/ks.yaml
  - ./wikijs/ks.yaml