---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: radarr
  namespace: media
spec:
  components:
    - ../../../../components/oidc/envoy
    - ../../../../components/kopiur/backup
    - ../../../../components/postgres/cert
  dependsOn:
    - name: cloudnative-pg-cluster
      namespace: databases
    - name: kopiur
      namespace: kopiur-system
    - name: pocket-id
      namespace: security
  interval: 30m
  path: ./kubernetes/apps/media/radarr/app
  postBuild:
    substitute:
      APP: radarr
      APP_ICON_URL: "https://cdn.jsdelivr.net/gh/selfhst/icons/svg/radarr.svg"
      OIDC_APP_NAME: Movies (Radarr)
      KOPIUR_CAPACITY: 5Gi
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true 
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  timeout: 5m
  wait: false