---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: soularr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: soularr
  values:
    controllers:
      soularr:
        forceRename: soularr
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/mrusse/soularr
              tag: 1.2.2@sha256:c4f97924fabfce4e0de539d821ea7d20519b95c4815a707bacfc9d7212597f20
            env:
              SCRIPT_INTERVAL: 60
              TZ: ${TIMEZONE}
              WEBUI_PORT: 80
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 512Mi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
      media:
        type: nfs
        server: truenas.services
        path: /mnt/BigPool/Media
      config:
        type: secret
        name: "{{ .Release.Name }}-secret"
        globalMounts:
          - path: /data/config.ini
            subPath: config.ini
            readOnly: true

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: http

    service:
      app:
        controller: soularr
        forceRename: soularr
        ports:
          http:
            port: 80