---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cluster-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cluster-secrets
    template:
      data:
        SECRET_DOMAIN: "{{ .SECRET_DOMAIN }}"
        GARAGE_REGION: "{{ .Region }}"
        GARAGE_URL: "{{ .garageURL }}"
  dataFrom:
    - extract:
        key: domains
    - extract:
        key: Garage
