---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: whisper
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: whisper
  values:
    controllers:
      whisper :
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: rhasspy/wyoming-whisper
              tag: 3.3.1@sha256:258956d1508a042ae52ceca04da85f6e74e7fab81676e3678619b8047e88c721
            args: [
              "--device", "cpu",
              "--model", "auto",
              "--language", "en",
              "--beam-size", "0",
              "--debug"
            ]
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: &port 10300
                  failureThreshold: 6
                  periodSeconds: 10
              readiness: *probes
              startup: *probes
            resources:
              requests:
                cpu: 250m
                memory: 512Mi
              limits:
                memory: 2Gi
    service:
      app:
        ports:
          http:
            port: *port
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"