---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: kometa
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  concurrencyPolicy: Forbid
  schedule: "0 */4 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: kometa
              image: kometateam/kometa:v2.4.6@sha256:12753705405a647a703c7a8aec6f862de05831f296858c6791b940500d558a6f
              args: [ "--run", "--read-only-config" ]
              env:
                - name: KOMETA_CONFIG
                  value: /config/couchpotatocentral_config.yml
              defaultPodOptions:
                securityContext:
                  runAsNonRoot: true
                  runAsUser: 1000
                  runAsGroup: 1000
                  fsGroup: 1000
                  fsGroupChangePolicy: OnRootMismatch
              volumeMounts:
                - name: pvc
                  mountPath: /config
                - name: posters
                  mountPath: /posters
          volumes:
            - name: pvc
              persistentVolumeClaim:
                claimName: kometa
            - name: posters
              nfs:
                server: truenas.services
                path: /mnt/BigPool/Media/Posters
          restartPolicy: OnFailure