---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kopiur.home-operations.com/clusterrepository_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: ClusterRepository
metadata:
  name: garage
spec:
  allowedNamespaces:
    all: true
  backend:
    s3:
      auth:
        secretRef:
          name: kopiur-repository-secret
          namespace: kopiur-system
      bucket: kopiur
      endpoint: "${GARAGE_URL}"
      region: "${GARAGE_REGION}"
  encryption:
    passwordSecretRef:
      name: kopiur-repository-secret
      namespace: kopiur-system
      key: KOPIA_PASSWORD
  scheduleDefaults:
    timezone: America/New_York
  server:
    auth:
      secretRef:
        name: kopiur-ui
        namespace: kopiur-system
        usernameKey: KOPIUR_USERNAME
        passwordKey: KOPIUR_PASSWORD
