---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tracearr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: tracearr-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        COOKIE_SECRET: "{{ .COOKIE_SECRET }}"
        DATABASE_URL: postgres://{{ .TIMESCALE_APP_USERNAME }}:{{ .TIMESCALE_APP_PASSWORD }}@timescale-rw.databases:5432/tracearr
        JWT_SECRET: "{{ .JWT_SECRET }}"
  dataFrom:
    - extract:
        key: tracearr