---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/volsync.backube/kopiamaintenance_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: KopiaMaintenance
metadata:
  name: daily
spec:
  enabled: true
  trigger:
    schedule: 30 3,15 * * *
  moverVolumes:
    - mountPath: repository
      volumeSource:
        nfs:
          path: /mnt/BigPool/Backups/Kopia/main
          server: truenas.services
  repository:
    repository: volsync-maintenance-secret
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/volsync.backube/kopiamaintenance_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: KopiaMaintenance
metadata:
  name: daily-fast
spec:
  enabled: true
  trigger:
    schedule: 30 5,17 * * *
  moverVolumes:
    - mountPath: repository
      volumeSource:
        nfs:
          path: /mnt/SmallPool/Backups/kopia-main
          server: truenas.services
  repository:
    repository: volsync-maintenance-secret