---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/k8s.cni.cncf.io/networkattachmentdefinition_v1.json
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: network
  namespace: virtualization
spec:
  config: |-
    {
      "cniVersion": "1.0.0",
      "name": "network",
      "plugins": [
        {
          "type": "macvlan",
          "master": "bond0.10",
          "mode": "bridge"
        }
      ]
    }