---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu-test
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      labels:
        kubevirt.io/vm: ubuntu-test
    spec:
      evictionStrategy: LiveMigrateIfPossible
      domain:
        clock:
          utc: {}
        cpu:
          cores: 2
        resources:
          requests:
            memory: 4G
        devices:
          inputs:
            - type: tablet
              bus: usb
              name: tablet
          disks:
            # - bootOrder: 1 ##Force ISO Boot
            #   name: cdromiso ##Installer ISO
            #   cdrom:
            #     bus: sata
            - name: ubuntu-test
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
            macAddress: "02:00:00:00:00:01"
      networks:
        - name: default
          pod: {}
      volumes:
        - name: ubuntu-test
          persistentVolumeClaim:
            claimName: ubuntu-test
        # - name: cdromiso ##Installer ISO
        #   persistentVolumeClaim:
        #     claimName: ubuntu-26-04-desktop