---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu-test
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      labels:
        kubevirt.io/vm: ubuntu-test
    spec:
      evictionStrategy: None
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - main-8
      domain:
        clock:
          utc: {}
        cpu:
          cores: 2
        resources:
          requests:
            memory: 4G
        devices:
          hostDevices:
            - name: p2000
              deviceName: nvidia.com/p2000
            - name: p2000-audio
              deviceName: nvidia.com/p2000-audio
          inputs:
            - type: tablet
              bus: usb
              name: tablet
          disks:
            # - bootOrder: 1 ##Force ISO Boot
            #   name: cdromiso ##Installer ISO
            #   cdrom:
            #     bus: sata
            - name: ubuntu-test
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
            macAddress: "02:00:00:00:00:01"
            ## TODO: Fix Cluster DNS/Cilium
            ## Workaround in netplan to bypass DNS routing issue in cluster
            # network:
            #   version: 2
            #   ethernets:
            #     enp1s0:
            #       dhcp4: true
            #       dhcp4-overrides:
            #         use-dns: false
            #       nameservers:
            #         addresses: [10.1.20.1]
      networks:
        - name: default
          pod: {}
      volumes:
        - name: ubuntu-test
          persistentVolumeClaim:
            claimName: ubuntu-test
        # - name: cdromiso ##Installer ISO
        #   persistentVolumeClaim:
        #     claimName: ubuntu-26-04-desktop