---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: karakeep
spec:
  components:
    - ../../../../components/kopiur/backup
    - ../../../../components/kopiur/migrate
  dependsOn:
    - name: kopiur
      namespace: kopiur-system
  interval: 30m
  path: ./kubernetes/apps/default/karakeep/app
  postBuild:
    substitute:
      APP: karakeep
      KOPIUR_CAPACITY: 10Gi
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true 
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  timeout: 5m
  wait: false