---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slskd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: slskd-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        slskd.yaml: |
          debug: false
          headless: false
          remoteConfiguration: true
          remoteFileManagement: false
          instanceName: default
          flags:
            noLogo: false
            noStart: false
            noConfigWatch: false
            noConnect: false
            noShareScan: false
            forceShareScan: false
            forceMigrations: false
            noVersionCheck: false
            logSQL: false
            logUnobservedExceptions: false
            experimental: false
            volatile: false
            caseSensitiveRegEx: false
            legacyWindowsTcpKeepalive: false
            optimisticRelayFileInfo: false
            noSqlitePooling: false
          relay:
            enabled: false
            mode: controller
            controller:
              address: null
              ignoreCertificateErrors: false
              apiKey: null
              secret: null
              downloads: false
            agents: {}
          permissions:
            file:
              mode: null
          directories:
            incomplete: /cache
            downloads: /media/Downloads/music
          shares:
            directories:
              - /media/Music
            filters:
              - \.ini$
              - Thumbs.db$
              - \.DS_Store$
            cache:
              storageMode: memory
              workers: 12
              retention: null
          global: null
          groups: null
          transfers:
            upload:
              slots: 10
              speedLimit: 2147483647
              limits:
                queued:
                  files: null
                  megabytes: null
                  failures: null
                daily:
                  files: null
                  megabytes: null
                  failures: null
                weekly:
                  files: null
                  megabytes: null
                  failures: null
            download:
              slots: 2147483647
              speedLimit: 2147483647
            groups:
              default:
                upload:
                  priority: 1
                  strategy: roundrobin
                  slots: 2147483647
                  speedLimit: 2147483647
                  limits:
                    queued:
                      files: null
                      megabytes: null
                      failures: null
                    daily:
                      files: null
                      megabytes: null
                      failures: null
                    weekly:
                      files: null
                      megabytes: null
                      failures: null
              leechers:
                thresholds:
                  files: 1
                  directories: 1
                upload:
                  priority: 1
                  strategy: roundrobin
                  slots: 2147483647
                  speedLimit: 2147483647
                  limits:
                    queued:
                      files: null
                      megabytes: null
                      failures: null
                    daily:
                      files: null
                      megabytes: null
                      failures: null
                    weekly:
                      files: null
                      megabytes: null
                      failures: null
              blacklisted:
                members: []
                cidrs: []
              userDefined: {}
          blacklist:
            enabled: false
            file: null
          filters:
            search:
              request: []
          rooms: []
          web:
            port: 80
            ipAddress: null
            socket: null
            https:
              disabled: false
              port: 5031
              ipAddress: null
              force: false
              certificate:
                pfx: null
                password: null
            urlBase: /
            contentPath: wwwroot
            logging: false
            authentication:
              disabled: true
          retention:
            search: null
            transfers:
              upload:
                succeeded: null
                errored: null
                cancelled: null
                failed: null
              download:
                succeeded: null
                errored: null
                cancelled: null
                failed: null
            files:
              complete: null
              incomplete: null
            logs: 180
          throttling:
            search:
              incoming:
                concurrency: 10
                circuitBreaker: 500
                responseFileLimit: 500
          logger:
            loki: null
            disk: false
            noColor: false
          metrics:
            enabled: false
            url: /metrics
            authentication:
              disabled: false
              username: slskd
              password: "*****"
          feature:
            swagger: false
          soulseek:
            address: vps.slsknet.org
            port: 2271
            username: {{ .SLSKD_SLSK_USERNAME }}
            password: {{ .SLSKD_SLSK_PASSWORD }}
            description: A slskd user. https://github.com/slskd/slskd
            picture: null
            listenIpAddress: 0.0.0.0
            listenPort: 25827
            diagnosticLevel: info
            distributedNetwork:
              disabled: false
              disableChildren: false
              childLimit: 25
              logging: false
            connection:
              timeout:
                connect: 10000
                inactivity: 15000
                transfer: 60000
              buffer:
                read: 16384
                write: 16384
                transfer: 262144
                writeQueue: 50
              proxy:
                enabled: false
                address: null
                port: null
                username: null
                password: null
          integration: null
          integrations:
            vpn:
              enabled: false
              portForwarding: false
              pollingInterval: 2500
              gluetun:
                version: 1
                url: null
                timeout: 1000
                username: null
                password: null
                apiKey: null
            webhooks: {}
            scripts: {}
            ftp:
              enabled: false
              address: null
              port: 21
              encryptionMode: auto
              ignoreCertificateErrors: false
              username: null
              password: null
              remotePath: /
              overwriteExisting: true
              connectionTimeout: 5000
              retryAttempts: 3
            pushbullet:
              enabled: false
              accessToken: null
              notificationPrefix: "From slskd:"
              notifyOnPrivateMessage: true
              notifyOnRoomMention: true
              retryAttempts: 3
              cooldownTime: 900000
  dataFrom:
    - extract:
        key: slskd