---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: slskd
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: slskd
  values:
    controllers:
      slskd:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/slskd/slskd
              tag: 0.25.1@sha256:ab9ed50e028b524cefdb7c1dd8ebca368a076e18441ee8ac2326473eb850b4c3
            env:
              SLSKD_SLSK_DIAG_LEVEL: debug
              APP_DIR: /config
              SLSKD_DOWNLOADS_DIR: /media/Downloads/music
              SLSKD_SHARE_CACHE_STORAGE_MODE: disk
              SLSKD_SHARE_CACHE_WORKERS: 2
              SLSKD_SHARE_CACHE_RETENTION: 10080
              SLSKD_INCOMPLETE_DIR: /cache
              SLSKD_SLSK_LISTEN_PORT: 25827
              SLSKD_HTTP_PORT: &port 80
              SLSKD_SHARED_DIR: /media/Music
              SLSKD_SHARE_FILTER: '\.ini$;Thumbs.db$;\.DS_Store$'
              SLSKD_NO_AUTH: true
              TZ: America/New_York
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 1Gi
    defaultPodOptions:
      annotations:
        k8s.v1.cni.cncf.io/networks: |-
          [{
            "name": "vpn",
            "namespace": "kube-system",
            "ips": ["10.1.66.5/24"],
            "mac": "00:00:10:01:66:05"
          }]
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.noms.tv"
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      cache:
        existingClaim: "{{ .Release.Name }}-cache"
      config:
        existingClaim: "{{ .Release.Name }}"
      media:
        type: nfs
        server: truenas.internal
        path: /mnt/BigPool/Media