---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app paperless-tika
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: paperless
  values:
    controllers:
      *app :
        containers:
          app:
            image:
              repository: apache/tika
              tag: 3.3.0.0@sha256:2a565f1ea1290bdcb74a7d35957d16a989ed44ef98790dcdcc28121d728fa583
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: &port 9998
                  failureThreshold: 6
                  periodSeconds: 10
              readiness: *probes
              startup: *probes
    service:
      app:
        ports:
          http:
            port: *port