---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: n8n-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DB_POSTGRESDB_USER: "{{ .MAIN_APP_USERNAME }}"
        DB_POSTGRESDB_PASSWORD: "{{ .MAIN_APP_PASSWORD }}"
  dataFrom:
    - extract:
        key: cloudnative-pg