---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: paperless
    template:
      engineVersion: v2
      data:
        PAPERLESS_URL: "{{ .URL }}"
        PAPERLESS_ALLOWED_HOSTS: "{{ .allowedHosts }}"
        PAPERLESS_SECRET_KEY: "{{ .secretKey }}"
        PAPERLESS_SOCIALACCOUNT_PROVIDERS: >
            {
              "openid_connect": {
                "OAUTH_PKCE_ENABLED": "True",
                "APPS": [
                  {
                    "provider_id": "pocketid",
                    "name": "PocketID",
                    "client_id": "{{ .oidClientID }}",
                    "secret": "{{ .oidClientSecret }}",
                    "settings": {
                      "server_url": "{{ .issuerURL }}",
                      "fetch_userinfo": true
                    }
                  }
                ],
                "SCOPE": ["openid", "profile", "email"]
              }
            }
        PAPERLESS_LOGOUT_REDIRECT_URL: "{{ .logoutURL }}"
  dataFrom:
    - extract:
        key: paperless
    - extract:
        key: pocket-id