---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bambuddy
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: bambuddy
  values:
    controllers:
      bambuddy:
        forceRename: bambuddy
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/maziggy/bambuddy
              tag: 1.2.5.2@sha256:954d93d7aaf98436cd8a31f67246d12453aa401830c34b8b645effc009caa897
            securityContext:
              capabilities:
                add:
                  - NET_BIND_SERVICE
            env:
              POSTGRES_USER:
                valueFrom:
                  secretKeyRef:
                    name: bambuddy-postgres
                    key: username
              POSTGRES_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: bambuddy-postgres
                    key: password
              POSTGRES_HOST:
                valueFrom:
                  secretKeyRef:
                    name: bambuddy-postgres
                    key: host
              POSTGRES_DB:
                valueFrom:
                  secretKeyRef:
                    name: bambuddy-postgres
                    key: database
              DATABASE_URL:
                value: "postgresql+asyncpg://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST)/$(POSTGRES_DB)"
                dependsOn:
                  - POSTGRES_USER
                  - POSTGRES_PASSWORD
                  - POSTGRES_HOST
                  - POSTGRES_DB
              PUID: 1000
              PGID: 1000
              PORT: 8080
              VIRTUAL_PRINTER_PASV_ADDRESS: 10.1.20.26
              TZ: ${TIMEZONE}
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi

      bambu-studio-api:
        forceRename: bambu-studio-api
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/maziggy/bambu-studio-api
              tag: bambuddy-1.2.5.2@sha256:107106d0e750055e6f817179f3ba0549d4d6ccd8ac5dd45be379f8e7611d323e
            env:
              NODE_ENV: production
              PORT: 3000
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true


    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000

    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /app/data
            subPath: data
          - path: /app/logs
            subPath: logs
          - path: /app/data/backups
            subPath: backups

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: bambuddy
                port: http

    service:
      bambuddy:
        controller: bambuddy
        forceRename: bambuddy
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 10.1.20.26
        ports:
          http:
            port: 8080
      bambu-studio-api:
        controller: bambu-studio-api
        forceRename: bambu-studio-api
        ports:
          http:
            port: 3000
