---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgbackweb
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: pgbackweb-secret
    template:
      engineVersion: v2
      data:
        PBW_ENCRYPTION_KEY: "{{ .PBW_ENCRYPTION_KEY }}"
        PBW_POSTGRES_CONN_STRING: "postgresql://{{ .MAIN_APP_USERNAME }}:{{ .MAIN_APP_PASSWORD }}@main-pooler-rw.databases:5432/pgbackweb"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: PGBackWeb