---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: systemrescue
spec:
  source:
    http:
      url: "https://fastly-cdn.system-rescue.org/releases/13.00/systemrescue-13.00-amd64.iso"
  storage:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 2Gi
    storageClassName: ceph-filesystem