---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: virtualization
resources:
  ## Requisites
  - ./namespace.yaml
  ## Deployments
  - ./cdi/ks.yaml
  - ./images/ks.yaml
  - ./kubevirt/ks.yaml
  # - ./swin/ks.yaml