---
apiVersion: v1
kind: Namespace
metadata:
  name: _
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    kubevirt.io: ""
    pod-security.kubernetes.io/enforce: "privileged"
