---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pocket-id-operator
spec:
  interval: 1h
  path: ./kubernetes/apps/security/pocket-id/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: security
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app pocket-id
spec:
  components:
    - ../../../../components/postgres/cert
  dependsOn:
    - name: cloudnative-pg-cluster
      namespace: databases
    - name: pocket-id-operator
  interval: 1h
  path: ./kubernetes/apps/security/pocket-id/instance
  postBuild:
    substitute:
      APP: *app
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: security
  wait: false
