---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aurral
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: aurral-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SOULSEEK_USERNAME: "{{ .SLSKD_SLSK_USERNAME }}"
        SOULSEEK_PASSWORD: "{{ .SLSKD_SLSK_PASSWORD }}"
  dataFrom:
    - extract:
        key: slskd