---
# yaml-language-server: $schema=https://crd.movishell.pl/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: patchmon
  labels:
    app: patchmon
spec:
  cluster:
    name: main-db
  name: patchmon
  owner: app