---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: explo
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: explo-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        LISTENBRAINZ_USER: "{{ .LISTENBRAINZ_USER }}"
        SYSTEM_USERNAME: "{{ .SYSTEM_USERNAME }}"
        SYSTEM_PASSWORD: "{{ .SYSTEM_PASSWORD }}"
        SLSKD_API_KEY: "{{ .SLSKD_API_KEY }}"
  dataFrom:
    - extract:
        key: explo