---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: explo
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: explo-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DISCOVERY_SERVICE: listenbrainz
        LISTENBRAINZ_USER: nomsplease
        EXPLO_SYSTEM: plex
        SYSTEM_URL: http://plex:32400
        API_KEY: "{{ .PlexToken }}"
        LIBRARY_NAME: Music
  dataFrom:
    - extract:
        key: plex