---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wikijs
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: wikijs
    template:
      engineVersion: v2
      data:
        DB_TYPE: postgres
        DB_HOST: main-rw.databases
        DB_PORT: "5432"
        DB_PASS: "{{ .MAIN_APP_PASSWORD }}" 
        DB_NAME: wikijs
        DB_USER: "{{ .MAIN_APP_USERNAME }}"
  dataFrom:
    - extract:
        key: cloudnative-pg