---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wikijs
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: wikijs
  values:
    controllers:
      wikijs:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: requarks/wiki
              tag: 2.5.314
            env:
              DB_TYPE: postgres
              DB_HOST: pooler-rw.databases.svc
              DB_PORT: "5432"
              DB_NAME: "{{ .Release.Name }}"
              DB_USER: "{{ .Release.Name }}"
              DB_SSL: "true"
              DB_SSLOPTIONS_CA: /var/run/secrets/root-ca/ca.crt
              DB_SSLOPTIONS_CERT: /var/run/secrets/postgresql/tls.crt
              DB_SSLOPTIONS_KEY: /var/run/secrets/postgresql/tls.key
              TZ: ${TIMEZONE}
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: &port 3000
                  failureThreshold: 6
                  periodSeconds: 10
              readiness: *probes
              startup: *probes
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "wiki.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https